{button} = require './DOM'

module.exports = button.withStyle 'Button',
  outline: 'none'
  display: 'inlineBlock'
  whiteSpace: 'nowrap'
  verticalAlign: 'middle'
  MsTouchAction: 'manipulation'
  touchAction: 'manipulation'
  cursor: 'pointer'
  WebkitUserSelect: 'none'
  MozUserSelect: 'none'
  MsUserSelect: 'none'
  userSelect: 'none'
  backgroundImage: 'none'
